/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,jsx,ts,tsx}"],
  theme: {
    extend: {
      colors: {
        "background-background-primary": "#fff",
        "default-grey": "#b8b8b8",
        "text-text-dark": "#1a0a03",
        "background-background-secondary": "#f0f0f0",
        "default-color-primary": "#dc5b19",
        "background-grey-light": "#f7f7f7",
        "accent-danger-accent": "#cc2610",
        mistyrose: "#f4d8d8",
        royalblue: "#5f69c7",
        "accent-ongoing-accent": "#f1ae11",
        "default-color-primary-light": "#ffece2",
        "secondary-gray": "#5d5e60",
        "text-text-dark-secondary": "#767676",
        "accent-accent-success": "#00a441",
        honeydew: "#d7ffe7",
        "text-text-dark1": "#000707",
        "default-color-primary1": "#0c6665",
      },
      spacing: {
        bigger: "48px",
        mediium: "12px",
        regular: "8px",
        normal: "24px",
        "very-big": "24px",
        regular1: "8px",
        small: "4px",
        small1: "20px",
        small2: "4px",
        smaller: "2px",
        smaller1: "16px",
        mediium1: "12px",
        small3: "20px",
        mediium2: "12px",
        smaller2: "16px",
        smaller3: "2px",
        small4: "20px",
        small5: "4px",
        smaller4: "2px",
        smaller5: "16px",
        "device-padding": "20px",
        normal1: "24px",
        smaller6: "16px",
        mediium3: "12px",
        regular4: "8px",
      },
      fontFamily: {
        "button-button-text-secondary": "'Encode Sans Expanded'",
        "text-description-text": "Montserrat",
      },
      borderRadius: {
        xl: "20px",
        "12xs-5": "0.5px",
        regular: "8px",
        regular1: "8px",
        regular2: "12px",
        small3: "20px",
        regular3: "12px",
        small4: "20px",
        smaller5: "16px",
        big: "24px",
        regular4: "8px",
      },
    },
    fontSize: {
      base: "16px",
      xs: "12px",
      sm: "14px",
      "3xs": "10px",
      "5xl": "24px",
      inherit: "inherit",
    },
    screens: {
      mq750: {
        raw: "screen and (max-width: 750px)",
      },
      mq450: {
        raw: "screen and (max-width: 450px)",
      },
    },
  },
  corePlugins: {
    preflight: false,
  },
};
